### PR TITLE
fix: use vector store docs as the default data source instead of remo…

### PR DESCRIPTION
**Pull request by dwelch-spike**
…ved pdf

### CODE REVIEW

**Comment by dwelch-spike** [comment]
I fiddled with this for a while, tried to get better answers with more data sources etc, a small tweak to the prompt ended up making things better. Here is a sample/...

image

**Comment by dwelch-spike** [comment]
@hev you need to `cd` into the langchain project directory before adding the template repo to the project. I'll add a note about this to the readme in the PR.

**Comment by hev** [comment]
I made it further this time (it does say to cd into the directory in the tool actually), but got the following.
Cursor_and_langchain_serve

**Comment by dwelch-spike** [comment]
@hev I needed to add "bs4" to the pyproject.toml as a dependency. It should work now.

**Review by hev — APPROVED** [review]
Looks good. I opened a docs tweak here - https://github.com/citrusleaf/aerospike-websites/pull/1721

**Pull request merged**
